### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by ghost** [gurkult/reagurk#47]
Add a footer to the website, looks plain.

**Comment by fisher60** [comment]
Yes, I think a footer would be a great idea. In the meantime it would need to automatically be stuck to the bottom as we still need more content to fill out the body of the site.

Would you be interested in working on this?

**Comment by ProfessorIgnoramus** [comment]
Yes! I actually dont know how to run the website locally though

**Comment by ProfessorIgnoramus** [comment]
Ok... I was working on it And i have made the footer but I am getting this error
![image](https://user-images.githubusercontent.com/92678790/143230473-a2caf1b8-5c35-4063-a386-f37f555b12eb.png)

**Comment by GDWR** [comment]
Looks to me like you are missing an export statement in the component module.

Take a look at how it was done in [hero.tsx](https://github.com/gurkult/reagurk/blob/main/reagurk/src/components/hero.tsx#L16)
if there are still issues with it. Might be worth creating a fork and pushing your changes so they can be viewed by other people.

Here is a [StackOverflow question](https://stackoverflow.com/questions/56577201/why-is-isolatedmodules-error-fixed-by-any-import/56577324) that is similar. Although I would recommend exporting the class, rather than nothing.

**Comment by ProfessorIgnoramus** [comment]
Ok thanks! I am done with the footer.

**Comment by GDWR** [comment]
Very nice, are you going to be making it into a [pull request](https://github.com/gurkult/reagurk/pulls)?

**Comment by DirectorDucky** [comment]
Can you check #dev-reagurk in the gurkult server?
Yes, I will make it a pull request

**Comment by GDWR** [comment]
I'm not on that server. Just browsing this repository.

**Comment by DirectorDucky** [comment]
oh

**Comment by PixelatedDeveloper** [comment]
![image](https://user-images.githubusercontent.com/92678790/145328042-0994710f-96d1-46d9-b968-834358d35eeb.png)

**Comment by PixelatedDeveloper** [comment]
Made a PR

**Comment by JustARandomDeveloper** [comment]
I made the footer. It is a pull request. Here is what it looks like:

![image](https://user-images.githubusercontent.com/95855603/145515323-ea0f0713-d9b5-4b5c-a22f-38b9a410ce04.png)

It is sticky, so you can add more stuff above it.
